import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sourceHanSerifSc = localFont({
  src: [
    {
      path: "./fonts/SourceHanSerifSC-VF.otf.woff2",
      weight: "200 900",
      style: "normal",
    },
  ],
  variable: "--font-source-han-serif-sc",
  display: "swap",
});

const yozai = localFont({
  src: [
    {
      path: "./fonts/Yozai-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Yozai-Medium.ttf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-yozai",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sourceHanSerifSc.variable} ${yozai.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
